<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">

                        <button type="button" class="decreaseQty" onclick="var qty_el = document.getElementById('qty') ; var qty = qty_el.value; if( !isNaN( qty ) && qty > 1 ) qty_el.value--;return false;">-</button>
                        <input type="number" id="qty" name="qty" class="input-text qty" value="<?= /* @noEscape */ $block->getProductDefaultQty() ?>" min="0" onchange="var input_el = this; var qty = input_el.value; if( isNaN( qty ) || qty < 1 ) input_el.value = 0;" />
                        <button type="button" class="increaseQty" onclick="var qty_el = document.getElementById('qty'); var qty = qty_el.value; if( !isNaN( qty )) qty_el.value++;return false;">+</button>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart" id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
            <?php
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('ask_specialist')
                ->toHtml();
            ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
