<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
$isLoggedIn = false;
if ($block->isLoggedIn()) {
	$dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
	<?php if ($block->isLoggedIn()) : ?>
		<a href="<?php echo $block->getUrl('customer/account/logout', ['_secure' => true]); ?>"><?= __('Logout'); ?></a>
	<?php else : ?>
		<a href="<?php echo $block->getUrl('customer/account/login', ['_secure' => true]); ?>"><?= __('My Account'); ?></a>
	<?php endif; ?>
</li>
